Repository cocoa-mhlw/cocoa, pull requests merged in 2021-11, with the labels that each got.

#460 Create preference_specification.md
  documents/content/docs/appendix/preference_specification.md
Labels: documentation

#468 Fix issue unexpected transition when updated term-of-service or privacy-policy.
  Covid19Radar/Covid19Radar/Destination.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ReAgreePrivacyPolicyPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ReAgreeTermsOfServicePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ReAgreePrivacyPolicyPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ReAgreeTermsOfServicePageViewModelTests.cs
Labels: bug

#469 Fix typos
  documents/content/docs/contribution/handling_pullreqeust.md
Labels: documentation

#483 Fix unexpected page transition on android
  Covid19Radar/Covid19Radar.Android/Services/ExposureNotificationApiService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Tutorial/TutorialPage4ViewModel.cs
Labels: COCOA2

#481 機能が重複しているメソッドの整理
  Covid19Radar/Covid19Radar/Common/PreferenceKey.cs
  Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
Labels: COCOA2

#485 [COCOA2]ReleaseビルドでAPI通信が行われない問題を修正
  Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
Labels: COCOA2

#494 ReportType, DaysSinceOnsetOfSymptomsが設定されていない（Missing）場合の取り扱い扱いを整備する
  src/Covid19Radar.Api.Common/Common/Constants.cs
  src/Covid19Radar.Api/Models/DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/Models/V1DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Background/Extentions/TemporaryExposureKeyExtension.cs
Labels: COCOA2

#498 DiagnosisKeyRepositoryのテスト追加
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/DiagnosisKeyRepositoryTests.cs
Labels: COCOA2

#496 Make V3Diagnosis-api idempotent.
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/V3DiagnosisApi.cs
Labels: COCOA2

#499 Rename class LogPathPlatformService to LocalPathService.
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
  Covid19Radar/Covid19Radar.Android/Services/LocalPathService.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar.iOS/Services/LocalPathService.cs
  Covid19Radar/Covid19Radar/Services/ILocalPathService.cs
  Covid19Radar/Covid19Radar/Services/Logs/LogPathService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Logs/LogPathServiceTests.cs
Labels: COCOA2

#507 Make compatible with Legacy-V1 mode.
  src/Covid19Radar.Api.Common/Common/Constants.cs
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/V3DiagnosisApi.cs
Labels: COCOA2

#508 Change DaysSinceOnsetOfSymptomsMissingValue.
  src/Covid19Radar.Api.Common/Common/Constants.cs
Labels: COCOA2

#482 `DiagnosisKeysDataMapping` can be updated after 7+ days since last updated.
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Covid19Radar/Common/DateTimeUtility.cs
  Covid19Radar/Covid19Radar/Common/PreferenceKey.cs
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Covid19Radar/Services/ILocalPathService.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Covid19Radar.UnitTests.csproj
  Covid19Radar/Tests/Covid19Radar.UnitTests/Files/exposure_configuration1.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/Files/exposure_configuration2.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/Files/exposure_configuration_update_infectiousness_for_days_since_onset_of_symptoms.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/HttpClientUtils.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/DiagnosisKeyRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureConfigurationRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/UserDataRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/TestDataUtils.cs
  TempNugetFeed/Chino.Android.1.0.0-rc05.nupkg
  TempNugetFeed/Chino.Android.1.0.0-rc06.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc05.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc06.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc05.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc06.nupkg
Labels: COCOA2

#518 Hot fix 517
  Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs
Labels: bug

#514 Use DeviceVerifierMock on all build configuration.
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
Labels: COCOA2

#511 [COCOA2]登録失敗時の上限越えエラーでホームに戻る
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/NotifyOtherPageViewModelTests.cs
Labels: COCOA2

#527 Reproduce a critical bug that migration failed.
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Migration/MigrationServiceTests.cs
Labels: bug

#525 Fix an issue that migration failed when DateTime is DateTime.MinValue.
  COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
  Covid19Radar/Covid19Radar.Android/Assets/license.html
  Covid19Radar/Covid19Radar.iOS/Resources/license.html
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Model/TermsUpdateInfoModel.cs
  Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Migration/MigrationServiceTests.cs
Labels: bug

#513 PartitionKeyの取り扱いを改善する
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/V3DiagnosisApi.cs
Labels: COCOA2

#490 Update TemporaryExposureKeyExportFileFormat definition.
  src/Covid19Radar.Api.Common/Common/Constants.cs
  src/Covid19Radar.Api.Common/Models/TemporaryExposureKeyModel.cs
  src/Covid19Radar.Api.Tests/Protobuf/SignatureInfoTest.cs
  src/Covid19Radar.Api/Models/DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/Models/V1DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Background/Covid19Radar.Background.csproj
  src/Covid19Radar.Background/Extentions/TemporaryExposureKeyExtension.cs
  src/Covid19Radar.Background/Protobuf/TemporaryExposureKeyExportFileFormat.cs
  src/Covid19Radar.Background/Protobuf/TemporaryExposureKeyExportFileFormat.g.cs
  src/Covid19Radar.Background/Protobuf/TemporaryExposureKeyExportFileFormat.proto
  src/Covid19Radar.Background/Services/TemporaryExposureKeySignatureInfoService.cs
Labels: waiting-for-confirmation

#537 Cocoa2/conflict war5
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/ViewModels/HelpPage/SendLogCompletePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HelpPage/SendLogConfirmationPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HelpPage/SendLogCompletePage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HelpPage/SendLogCompletePageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HelpPage/SendLogConfirmationPageViewModelTests.cs
  src/Covid19Radar.Api.Common/Models/TemporaryExposureKeyModel.cs
  src/Covid19Radar.Background/Covid19Radar.Background.csproj
  src/Covid19Radar.Background/Protobuf/TemporaryExposureKeyExportFileFormat.cs
  src/Covid19Radar.Background/Services/TemporaryExposureKeySignatureInfoService.cs
Labels: COCOA2

#529 [Server] Set initial values to ReportType and DaysSinceOnsetOfSymptoms
  src/Covid19Radar.Api.Common/Models/TemporaryExposureKeyModel.cs
Labels: COCOA2
