Repository cocoa-mhlw/cocoa, pull requests merged in 2021-12, with the labels that each got.

#542 Cocoa2/merge no conflict
  Covid19Radar/Covid19Radar/Model/MainMenuModel.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs
  Covid19Radar/Covid19Radar/Templates/HelpMenuTemplate.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/HelpMenuPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/SubmitConsentPage.xaml
  Covid19Radar/Covid19Radar/Views/MenuPage.xaml
  azure-pipelines/app/app-build-adhoc-dev.yml
  azure-pipelines/app/app-build-adhoc-stg.yml
  azure-pipelines/app/app-build-store-prod.yml
  azure-pipelines/app/app-build-use-test-diagnosis-dev.yml
  azure-pipelines/app/app-build-use-test-diagnosis-stg.yml
  src/Covid19Radar.Api/DataAccess/CosmosUserRepository.cs
  src/Covid19Radar.Api/RegisterApi.cs
  src/pipelines/azure-pipelines.yml
Labels: COCOA2

#536 Update preference_specification.md
  documents/content/docs/appendix/preference_specification.md
Labels: documentation

#558 Cocoa2/merge no conflict
  .github/workflows/CI.yml
  documents/content/_index.md
  documents/content/agreements/_index.md
  documents/content/agreements/privacy_policy.md
  documents/content/agreements/terms_of_use.md
  documents/content/docs/appendix/preference_specification.md
  documents/content/docs/materials/_index.md
  documents/content/docs/materials/app_store/_index.md
  documents/content/docs/materials/goole_play/_index.md
  documents/content/docs/materials/goole_play/ja.html
  documents/content/materials/app_store/en.md
  documents/content/materials/app_store/ja.md
  documents/content/materials/app_store/zh_CN.md
  documents/content/materials/goole_play/en.md
  documents/content/materials/goole_play/ja.md
  documents/content/materials/goole_play/zh_CN.md
Labels: COCOA2

#541 Update Terms of use and privacy policy.
  documents/content/agreements/privacy_policy.md
  documents/content/agreements/terms_of_use.md
  documents/static/materials/agreements/privacy_policy/chinese_pp_00030.html
  documents/static/materials/agreements/privacy_policy/english_pp_00032.html
  documents/static/materials/agreements/privacy_policy/japanese_pp_00027.html
  documents/static/materials/agreements/privacy_policy/privacypolicy_chinese.html
  documents/static/materials/agreements/privacy_policy/privacypolicy_english.html
  documents/static/materials/agreements/privacy_policy/privacypolicy_japanese.html
  documents/static/materials/agreements/terms_of_use/chinese_rk_00029.html
  documents/static/materials/agreements/terms_of_use/english_rk_00031.html
  documents/static/materials/agreements/terms_of_use/japanese_rk_00028.html
  documents/static/materials/agreements/terms_of_use/kiyaku_chinese.html
  documents/static/materials/agreements/terms_of_use/kiyaku_english.html
  documents/static/materials/agreements/terms_of_use/kiyaku_japanese.html
Labels: documentation

#553 [COCOA2]AbsExposureDetectionBackgroundServiceのテスト
  Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/ILocalPathService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/AbsExposureDetectionBackgroundServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#560 Fix instantiate timing issue.
  src/Covid19Radar.Api/V3DiagnosisApi.cs
Labels: bug, COCOA2

#568 Cocoa2/conflict war6
  documents/content/agreements/privacy_policy.md
  documents/content/agreements/terms_of_use.md
  documents/static/materials/agreements/privacy_policy/chinese_pp_00030.html
  documents/static/materials/agreements/privacy_policy/english_pp_00032.html
  documents/static/materials/agreements/privacy_policy/japanese_pp_00027.html
  documents/static/materials/agreements/privacy_policy/privacypolicy_chinese.html
  documents/static/materials/agreements/privacy_policy/privacypolicy_english.html
  documents/static/materials/agreements/privacy_policy/privacypolicy_japanese.html
  documents/static/materials/agreements/terms_of_use/chinese_rk_00029.html
  documents/static/materials/agreements/terms_of_use/english_rk_00031.html
  documents/static/materials/agreements/terms_of_use/japanese_rk_00028.html
  documents/static/materials/agreements/terms_of_use/kiyaku_chinese.html
  documents/static/materials/agreements/terms_of_use/kiyaku_english.html
  documents/static/materials/agreements/terms_of_use/kiyaku_japanese.html
  src/Covid19Radar.Api.Common/Extensions/ENExtensions.cs
  src/Covid19Radar.Api.Tests/DiagnosisApiTest.cs
  src/Covid19Radar.Api.Tests/V3DiagnosisApiTest.cs
  src/Covid19Radar.Api/Models/IAndroidDeviceVerification.cs
  src/Covid19Radar.Api/Models/IAppleDeviceVerification.cs
  src/Covid19Radar.Api/Models/IDeviceVerification.cs
  src/Covid19Radar.Api/Models/V1DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
Labels: COCOA2

#571 [Server] Bump up Nuget packages version.
  src/Covid19Radar.Api.Common/Covid19Radar.Api.Common.csproj
  src/Covid19Radar.Api.Tests/Covid19Radar.Api.Tests.csproj
  src/Covid19Radar.Api/Covid19Radar.Api.csproj
  src/Covid19Radar.Background/Covid19Radar.Background.csproj
Labels: COCOA2

#530 [COCOA2]「登録失敗時の上限越えエラーでホームに戻る」のテスト追加と呼び出しメソッド変更
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/NotifyOtherPageViewModelTests.cs
Labels: COCOA2

#585 HomePageViewModel内のEN関連のテストを追加
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#604 Fixing Register button always disabled.
  Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
Labels: COCOA2

#611 [COCOA2] Azure Function上でMicrosoft.Extensions.Primitives.StringValuesのクラッシュが起きる問題対応
  src/Covid19Radar.Api.Common/Covid19Radar.Api.Common.csproj
  src/Covid19Radar.Api/Covid19Radar.Api.csproj
  src/Covid19Radar.Background/Covid19Radar.Background.csproj
Labels: COCOA2

#584 Replace dialog message string.Empty to null.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: COCOA2

#602 Fix the WorkManager scheduling issue.
  Covid19Radar/Covid19Radar.Android/MainActivity.cs
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
Labels: COCOA2

#609 第1期コードレビューを反映
  Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/DiagnosisKeyRegisterServer.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/settings.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/AppSettingsTests.cs
Labels: COCOA2

#610 Cocoa2/merge develop
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
Labels: COCOA2

#619 Fix V2DiagnosisApiTest.cs is in redundant folder.
  src/Covid19Radar.Api.Tests/V2DiagnosisApiTest.cs
Labels: COCOA2

#556 ExposureDetectionServiceのテスト追加
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Common/DeviceInfoUtility.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
Labels: COCOA2

#629 [COCOA2]接触通知対象外ユーザー向け画面: 低リスク表示のUI実装
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/LowRiskContactPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/LowRiskContactPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/LowRiskContactPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/LowRiskContactPageViewModelTests.cs
Labels: COCOA2

#631 Maintain server configuration.
  Covid19Radar/Covid19Radar/AppSettings.cs
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
  Covid19Radar/Covid19Radar/settings.json
Labels: COCOA2

#625 AppDelegateで取得するExposureConfigurationがnullになる不具合を修正
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  TempNugetFeed/Chino.Android.1.0.0-rc07.nupkg
  TempNugetFeed/Chino.Android.1.0.0-rc08.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc07.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc08.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc07.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc08.nupkg
  documents/content/docs/development/how_to_build.md
Labels: COCOA2

#637 [App] ClearText generating logic that App and Server must be equal.
  Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
  Covid19Radar/Covid19Radar/Common/DeviceVerifierUtils.cs
  Covid19Radar/Covid19Radar/Model/DiagnosisSubmissionParameter.cs
  Covid19Radar/Covid19Radar/Services/DiagnosisKeyRegisterServer.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Common/DeviceVerifierUtilsTests.cs
Labels: COCOA2

#640 陽性情報登録時に送信するTEKの範囲を変更する
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Common/TemporaryExposureKeyUtilsTest.cs
  src/Covid19Radar.Api.Tests/Models/V3DiagnosisSubmissionParameterTest.cs
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
Labels: COCOA2

#645 [COCOA2]接触通知対象外ユーザー向け画面: 低リスク接触なしのUI実装
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NoRiskContactPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/NoRiskContactPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/NoRiskContactPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
Labels: COCOA2
