Repository cocoa-mhlw/cocoa, pull requests merged in 2022-01, with the labels that each got.

#655 Handle exception from Cappuccino.
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
Labels: COCOA2

#654 Fix InquiryLog endpoint construction.
  Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Services/HttpDataService.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/EditServerConfigurationPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/Settings/EditServerConfigurationPage.xaml
Labels: COCOA2

#650 Fix save exposure-data process.
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Model/UserExposureSummary.cs
  Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Covid19Radar.UnitTests.csproj
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/UnionTests.cs
  TempNugetFeed/Chino.Android.1.0.0-rc08.nupkg
  TempNugetFeed/Chino.Android.1.0.0-rc09.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc08.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc09.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc08.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc09.nupkg
Labels: COCOA2

#647 [COCOA2]接触状況確認画面だしわけ
  Covid19Radar/Covid19Radar/App.xaml
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Model/ExposureCheckScoreModel.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/LowRiskContactPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NoRiskContactPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/ExposureCheckPage.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/ExposureCheckPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/NoRiskContactLayout.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/NoRiskContactLayout.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/LowRiskContactPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/NoRiskContactPage.xaml
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/LowRiskContactPageViewModelTests.cs
Labels: COCOA2

#479 Refactor navigation
  Covid19Radar/Covid19Radar.Android/MainActivity.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Extensions.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ReAgreePrivacyPolicyPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ReAgreeTermsOfServicePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ReAgreePrivacyPolicyPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ReAgreeTermsOfServicePage.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/SplashPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/SubmitConsentPage.xaml.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ReAgreePrivacyPolicyPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ReAgreeTermsOfServicePageViewModelTests.cs
Labels: COCOA2

#659 Cappuccinoのバージョンを更新（v1.0.0-rc10）する
  .github/workflows/CI.yml
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.Android/MainApplication.cs
  Covid19Radar/Covid19Radar.Android/Services/ExposureNotificationApiService.cs
  Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar.iOS/Services/ExposureNotificationApiService.cs
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureNotificationApiService.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/AbsExposureDetectionBackgroundServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/NotifyOtherPageViewModelTests.cs
  TempNugetFeed/Chino.Android.1.0.0-rc09.nupkg
  TempNugetFeed/Chino.Android.1.0.0-rc10.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc09.nupkg
  TempNugetFeed/Chino.Common.1.0.0-rc10.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc09.nupkg
  TempNugetFeed/Chino.iOS.1.0.0-rc10.nupkg
  TempNugetFeed/Debug/.gitkeep
  TempNugetFeed/Debug_Mock/.gitkeep
  TempNugetFeed/Release/Chino.Android.1.0.0-rc10.nupkg
  TempNugetFeed/Release/Chino.Common.1.0.0-rc10.nupkg
  TempNugetFeed/Release/Chino.iOS.1.0.0-rc10.nupkg
  TempNugetFeed/Xamarin.GooglePlayServices.Nearby.ExposureNotification.19.7.2-eap-alpha03.nupkg
  TempNugetFeed/Xamarin.GooglePlayServices.Nearby.ExposureNotification.19.7.2-eap-alpha04.nupkg
Labels: COCOA2

#668 接触情報の入出力をExposureDataRepositoryに分離する
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Repository/ExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ContactedNotifyPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureDataRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/UserDataRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposuresPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#680 Remove DebugDiagnosisKeyRegisterServer.
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Services/DebugDiagnosisKeyRegisterServer.cs
Labels: COCOA2

#614 [Server] RegisterApiのリファクタリング（ICryptionServiceの削除）
  src/Covid19Radar.Api.Common/Extensions/IConfigurationExtension.cs
  src/Covid19Radar.Api.Common/Services/CryptionService.cs
  src/Covid19Radar.Api.Common/Services/ICryptionService.cs
  src/Covid19Radar.Api.Tests/Common/Services/CryptionServiceTest.cs
  src/Covid19Radar.Api.Tests/RegisterApiTest.cs
  src/Covid19Radar.Api/RegisterApi.cs
  src/Covid19Radar.Api/Startup.cs
Labels: COCOA2

#671 Risk calculation
  Covid19Radar/Covid19Radar/Repository/ExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Covid19Radar/Services/ExposureRiskCalculationService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureDataRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureRiskCalculationServiceTests.cs
Labels: COCOA2

#683 NotContactPageの画面遷移、リソース等を削除
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
Labels: COCOA2

#685 Create HttpClient instance for every http-access.
  Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Services/EventLogService.cs
  Covid19Radar/Covid19Radar/Services/HttpDataService.cs
  Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/TermsUpdateServiceTests.cs
Labels: bug, COCOA2

#672 External file for risk calculation
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Model/ExposureRiskCalculationConfiguration.cs
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Covid19Radar/Services/ExposureRiskCalculationService.cs
  Covid19Radar/Covid19Radar/Services/ILocalPathService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ContactedNotifyPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/EditServerConfigurationPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/Settings/EditServerConfigurationPage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/Covid19Radar.UnitTests.csproj
  Covid19Radar/Tests/Covid19Radar.UnitTests/Files/exposure_risk_calculation_configuration_v1_1.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/Models/ExposureRiskCalculationConfigurationTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureRiskCalculationServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposuresPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
  documents/static/exposure_configuration/configuration.json
  documents/static/exposure_configuration/risk_calculation_configuration.json
Labels: COCOA2

#688 ホーム画面で「接触有無の最新確認日時」が更新されない問題を修正
  Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/AbsExposureDetectionBackgroundServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#696 ENv2用のパラメータの初期設定値を定義する
  documents/static/exposure_configuration/configuration.json
  documents/static/exposure_configuration/risk_calculation_configuration.json
Labels: COCOA2

#704 Default config
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  documents/static/exposure_configuration/configuration.json
Labels: COCOA2

#701 動作状況画面でシェアシートが表示されない
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
Labels: COCOA2

#714 Improve HttpClient handling.
  Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Services/EventLogService.cs
  Covid19Radar/Covid19Radar/Services/HttpDataService.cs
  Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/TermsUpdateServiceTests.cs
Labels: bug, COCOA2

#710 Update default AppleExposureConfigV2.
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
Labels: COCOA2

#715 Update Cappuccino.iOS version to v1.0.0-rc11
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2

#724 DebugPageに接触通知のLocalNotificationを追加
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
Labels: bug, COCOA2

#729 お問い合わせページからログを取得・共有できるようにする
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Services/DebugExposureDataCollectServer.cs
  Covid19Radar/Covid19Radar/Services/EventLogServiceNop.cs
  Covid19Radar/Covid19Radar/Services/Logs/ILogFileService.cs
  Covid19Radar/Covid19Radar/Services/Logs/ILogUploadService.cs
  Covid19Radar/Covid19Radar/Services/Logs/LogFileService.cs
  Covid19Radar/Covid19Radar/Services/Logs/LogUploadService.cs
  Covid19Radar/Covid19Radar/Services/Logs/LogUploadServiceNop.cs
  Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HelpPage/SendLogConfirmationPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HelpPage/InqueryPage.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/SendLogConfirmationPage.xaml.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Logs/LogFileServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Logs/LogUploadServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HelpPage/InqueryPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HelpPage/SendLogConfirmationPageViewModelTests.cs
Labels: beta

#730 Disable CheckVersion.
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Common/AppUtils.cs
  Covid19Radar/Covid19Radar/Services/CheckVersionService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: beta

#735 Improve local-notification on Android.
  Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
Labels: COCOA2

#725 ExposureRiskCalculationConfigurationRepository関連の例外ハンドリングの追加
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Services/DialogService.cs
  Covid19Radar/Covid19Radar/Services/IDialogService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ContactedNotifyPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ContactedNotifyPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: bug, COCOA2

#720 v2.0.0 リリースに向けてイベントログ（接触データ）送信機能を無効化する
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Covid19Radar/Common/PreferenceKey.cs
  Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
  Covid19Radar/Covid19Radar/Services/DebugExposureDataCollectServer.cs
  Covid19Radar/Covid19Radar/Services/EventLogService.cs
  Covid19Radar/Covid19Radar/Services/EventLogServiceNop.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
Labels: COCOA2

#738 Make InqueryTelephoneNumber invisible and show message that recommend…
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
Labels: beta

#740 Handle response 204 No Content as success.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: beta

#734 Merge conflict DailySummary at SetExposureDataAsync.
  Covid19Radar/Covid19Radar/Repository/ExposureDataRepository.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureDataRepositoryTests.cs
Labels: bug, COCOA2

#737 Refactoring.
  Covid19Radar/Covid19Radar/Services/EventLogService.cs
Labels: COCOA2

#741 Handle response 204 No Content as success.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2

#742 Show Risk-threshold on ExposureCheckPage.
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/ExposureCheckPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#751 Cocoa2/risk calculation combination
  Covid19Radar/Covid19Radar/Model/ExposureRiskCalculationConfiguration.cs
  Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
  Covid19Radar/Covid19Radar/Services/ExposureRiskCalculationService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ContactedNotifyPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Models/ExposureRiskCalculationConfigurationTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureRiskCalculationServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ContactedNotifyPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposuresPageViewModelTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#756 ENv2パラメータとリスクスコア閾値条件の変更
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  documents/static/exposure_configuration/configuration.json
  documents/static/exposure_configuration/risk_calculation_configuration.json
Labels: COCOA2

#759 Fix DiagnosisKeyListProvideServerEndpoint always null on release build.
  Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
Labels: bug, COCOA2

#763 Show LastConfirmedDate immediately when finished exposureDetection.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: bug, design, COCOA2

#766 Show beta suffix.
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
Labels: beta

#748 Fix an issue that ExposureRiskCalculationConfiguration never updated.
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Covid19Radar.UnitTests.csproj
  Covid19Radar/Tests/Covid19Radar.UnitTests/Files/exposure_risk_configuration1.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/Files/exposure_risk_configuration2.json
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureRiskCalculationConfigurationRepositoryTests.cs
Labels: bug, COCOA2

#753 接触確認画面への遷移前にローディングインジケータをだす
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: bug, COCOA2

#764 ログ出力の整備
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
Labels: enhancement, COCOA2

#773 Fixed an issue that unconfirmed status persisted even after Airplane …
  Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
Labels: bug, COCOA2

#770 Start the task ExposureDetection when ExposureNotification API is ena…
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
Labels: enhancement, COCOA2

#771 Filter exposure under 15 minutes
  Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
  Covid19Radar/Covid19Radar/Model/ExposureCheckScoreModel.cs
  Covid19Radar/Covid19Radar/Repository/ExposureDataRepositoryMock.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
Labels: design, COCOA2

#777 Show AlertDialog when connection failed to diagnosis-register server.
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Services/DiagnosisKeyRegisterServer.cs
  Covid19Radar/Covid19Radar/Services/HttpDataService.cs
  Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
  Covid19Radar/Covid19Radar/Services/IDiagnosisKeyRegisterServer.cs
  Covid19Radar/Covid19Radar/Services/IHttpDataService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/HttpDataServiceTests.cs
Labels: bug, COCOA2

#776 Fix an issue that Loading-dialog disappear unexpectedly when submitti…
  Covid19Radar/Covid19Radar/Services/DiagnosisKeyRegisterServer.cs
  Covid19Radar/Covid19Radar/Services/HttpDataService.cs
  Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
  Covid19Radar/Covid19Radar/Services/IDiagnosisKeyRegisterServer.cs
  Covid19Radar/Covid19Radar/Services/IHttpDataService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/HttpDataServiceTests.cs
Labels: bug, COCOA2

#785 Handle exception(or ApiResult) that getTekHistory was unauthorized.
  Covid19Radar/Covid19Radar.Android/MainActivity.cs
  Covid19Radar/Covid19Radar/IExposureNotificationEventCallback.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2

#781 Fix wrong state in HomePage when list.json obtained failed.
  Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
  Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/DiagnosisKeyRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/AbsExposureDetectionBackgroundServiceTests.cs
Labels: bug, COCOA2

#787 ライセンスファイルの差し替え
  Covid19Radar/Covid19Radar.Android/Assets/license.html
  Covid19Radar/Covid19Radar.iOS/Resources/license.html
Labels: bug, COCOA2

#779 Maintain language resources.
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
Labels: COCOA2

#789 Fix an issue that wrong == operator used.
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureRiskCalculationConfigurationRepositoryTests.cs
Labels: bug, COCOA2

#793 Change the value of transmissionRiskScores for iOS.
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  documents/static/exposure_configuration/Xamarin.ExposureNotification/Configration.json
  documents/static/exposure_configuration/configuration.json
Labels: COCOA2

#795 Set transmission risk level LOWEST to outdated diagnosis-keys.
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  documents/static/exposure_configuration/Xamarin.ExposureNotification/Configration.json
  documents/static/exposure_configuration/configuration.json
  src/Covid19Radar.Api/V3DiagnosisApi.cs
Labels: enhancement, COCOA2

#798 Improve log
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
Labels: enhancement, COCOA2

#806 Fix an issue that DatePicker hard to see.
  Covid19Radar/Covid19Radar.Android/Resources/values/styles.xml
  Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
Labels: bug, design, COCOA2, beta

#802 Fix an issue that progressdialog never dismiss.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2, beta

#797 Fix an issue that inappropriate equal operator.
  Covid19Radar/Covid19Radar/Common/PreferenceKey.cs
  Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureConfigurationRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
Labels: bug, COCOA2

#809 Fix an issue that background task unexpected behavior on iOS.
  Covid19Radar/Covid19Radar.iOS/Info.plist
  Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
Labels: bug, COCOA2, beta

#811 Bump up version to v2.0.0-beta02
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
Labels: beta

#812 Apply translation.
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
Labels: COCOA2

#819 Fix HomePage indicator is not updated when connection failed to server.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
Labels: bug, COCOA2

#817 Apply translation.
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
Labels: COCOA2

#822 Fix an issue that alert-dialog disappear unexpectedly when submitting…
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2

#828 Fix an issue that V1DiagnosisApi doesn't work.
  Covid19Radar/Covid19Radar/Common/DeviceVerifierUtils.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Common/DeviceVerifierUtilsTests.cs
  src/Covid19Radar.Api.Tests/Models/V1DiagnosisSubmissionParameterTest.cs
  src/Covid19Radar.Api.Tests/Models/V2DiagnosisSubmissionParameterTest.cs
  src/Covid19Radar.Api.Tests/Models/V3DiagnosisSubmissionParameterTest.cs
  src/Covid19Radar.Api/Models/V1DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/Models/V2DiagnosisSubmissionParameter.cs
  src/Covid19Radar.Api/Models/V3DiagnosisSubmissionParameter.cs
Labels: bug, COCOA2

#829 Task.Delayを入れてENのモーダルが閉じるのを待つ
  Covid19Radar/Covid19Radar.iOS/Services/ExposureNotificationApiService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2

#833 Fixed an issue that the result dialog was not displayed on Android.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs
Labels: bug, COCOA2

#825 Cocoa2/refine exposurecheck
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml
  Covid19Radar/Covid19Radar.Android/Resources/drawable-ja-xhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-ja-xxhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-xhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-xxhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-xxhdpi/exposure_check_page_head.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-zh-xhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-zh-xxhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/Nocontact10@2x.png
  Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/Nocontact10@3x.png
  Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/exposure_check_page_head.png
  Covid19Radar/Covid19Radar.iOS/Resources/ja.lproj/Nocontact10@2x.png
  Covid19Radar/Covid19Radar.iOS/Resources/ja.lproj/Nocontact10@3x.png
  Covid19Radar/Covid19Radar.iOS/Resources/zh-Hans.lproj/Nocontact10@2x.png
  Covid19Radar/Covid19Radar.iOS/Resources/zh-Hans.lproj/Nocontact10@3x.png
  Covid19Radar/Covid19Radar/App.xaml
  Covid19Radar/Covid19Radar/App.xaml.cs
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/Repository/ExposureRiskCalculationConfigurationRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ThankYouNotifyOtherPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/ExposureCheckPage.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/NoRiskContactLayout.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/NoRiskContactLayout.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ExposureCheckPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ExposureCheckPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ThankYouNotifyOtherPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ThankYouNotifyOtherPage.xaml.cs
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
Labels: design, COCOA2, beta
