Repository cocoa-mhlw/cocoa, pull requests merged in 2022-03, with the labels that each got.

#866 For preventing security incident, Git should ignore settings.json.
  .github/workflows/CI.yml
  Covid19Radar/Covid19Radar/Covid19Radar.csproj
  Covid19Radar/Covid19Radar/settings_template.json
  azure-pipelines/app/templates/build/setup/app-setup-variables-template.yml
  documents/content/docs/development/how_to_build.md
Labels: enhancement

#882 iOSでローカル通知をオフにしている場合に設定アプリへのリンクを出す
  Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
  Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Services/DialogService.cs
  Covid19Radar/Covid19Radar/Services/IDialogService.cs
  Covid19Radar/Covid19Radar/Services/ILocalNotificationService.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/HomePage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: enhancement

#915 Revert TabIndex
  Covid19Radar/Covid19Radar/Views/ExposureCheck/LowRiskContactLayout.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/HelpMenuPage.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage1.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage2.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage3.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/HelpPage4.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/InqueryPage.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/SendLogCompletePage.xaml
  Covid19Radar/Covid19Radar/Views/HelpPage/SendLogConfirmationPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/HomePage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/HowToReceiveProcessingNumberPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/NotifyOtherPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/PrivacyPolicyPage2.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ReAgreePrivacyPolicyPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ReAgreeTermsOfServicePage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/SubmitConsentPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/TermsofservicePage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/TroubleshootingPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/WebAccessibilityPolicyPage.xaml
  Covid19Radar/Covid19Radar/Views/MenuPage.xaml
  Covid19Radar/Covid19Radar/Views/Settings/LicenseAgreementPage.xaml
  Covid19Radar/Covid19Radar/Views/Settings/SettingsPage.xaml
  Covid19Radar/Covid19Radar/Views/Tutorial/PrivacyPolicyPage.xaml
  Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage1.xaml
  Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage2.xaml
  Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage3.xaml
  Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage4.xaml
  Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage6.xaml
Labels: bug

#893 パブリックβ版の説明ドキュメントを作成する
  documents/content/docs/contribution/open_beta_version.md
Labels: documentation, beta

#912 Fix ReAgree*Page are not launched from DebugPage.
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
Labels: bug
