Repository cocoa-mhlw/cocoa, pull requests merged in 2022-02, with the labels that each got.

#837 Fix device verification v1
  Covid19Radar/Covid19Radar/Common/DeviceVerifierUtils.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Common/DeviceVerifierUtilsTests.cs
  src/Covid19Radar.Api.Tests/Models/V1DiagnosisSubmissionParameterTest.cs
  src/Covid19Radar.Api/Models/V1DiagnosisSubmissionParameter.cs
Labels: bug, COCOA2

#849 Improve ExposureCheckPage behavior.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs
Labels: COCOA2

#851 ExposureData will be saved to SecureStorage.
  Covid19Radar/Covid19Radar/Repository/ExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Tests/Covid19Radar.UnitTests/Repository/ExposureDataRepositoryTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/Services/ExposureDetectionServiceTests.cs
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/HomePageViewModelTests.cs
Labels: COCOA2

#852 LowRiskExposurePage is closed temporary.
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/ExposureCheck/ExposureCheckPage.xaml
  Covid19Radar/Covid19Radar/Views/ExposureCheck/NoRiskContactLayout.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
Labels: COCOA2

#853 Connect to V2DiagnosisApi.
  Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
  Covid19Radar/Covid19Radar/Common/AppConstants.cs
  Covid19Radar/Covid19Radar/Model/DiagnosisSubmissionParameter.cs
Labels: COCOA2

#844 保存されているExposureWindowをデバッグメニューからCSVでエクスポートする
  Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
Labels: COCOA2

#854 Add padding to button
  Covid19Radar/Covid19Radar/App.xaml
Labels: design

#863 Beta/contact notify
  Covid19Radar/Covid19Radar/Repository/IExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ExposureCheckPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ExposuresPage.xaml
Labels: COCOA2, beta

#826 Bump up version to v2.0.0-beta03
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
Labels: COCOA2, beta

#868 Fixed an issue that exposure duration was always displayed.
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposureCheckPageViewModel.cs
Labels: bug, COCOA2, beta

#874 v2.0.0-betaで受け取った通知は検査費用が公費負担にはならない点を記述した
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/SplashPage.xaml
Labels: COCOA2, beta

#878 Clarify exposure date AM or PM.
  Covid19Radar/Covid19Radar/Repository/IExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
Labels: COCOA2, beta

#876 Change version_suffix to openbeta01.
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
Labels: COCOA2, beta

#875 「陽性者との接触は確認されませんでした」ページを旧版に戻す
  Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
  Covid19Radar/Covid19Radar.Android/Resources/drawable-ja-xhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-ja-xxhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-xhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-xxhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-zh-xhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.Android/Resources/drawable-zh-xxhdpi/Nocontact10.png
  Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
  Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/Nocontact10@2x.png
  Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/Nocontact10@3x.png
  Covid19Radar/Covid19Radar.iOS/Resources/ja.lproj/Nocontact10@2x.png
  Covid19Radar/Covid19Radar.iOS/Resources/ja.lproj/Nocontact10@3x.png
  Covid19Radar/Covid19Radar.iOS/Resources/zh-Hans.lproj/Nocontact10@2x.png
  Covid19Radar/Covid19Radar.iOS/Resources/zh-Hans.lproj/Nocontact10@3x.png
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ExposureCheckPage.xaml
  Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ExposureCheckPageViewModelTests.cs
Labels: COCOA2, beta

#886 [オープンベータ向け]「過去14日間の接触」画面の表示を改善する
  Covid19Radar/Covid19Radar/Repository/IExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
Labels: design, COCOA2, beta

#885 [クローズドベータ向け]「過去14日間の接触」画面の表示を改善する
  Covid19Radar/Covid19Radar/Repository/IExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
Labels: design, COCOA2, beta

#888 v2.0.0ブランチの変更をdevelopに反映する
  Covid19Radar/Covid19Radar/Repository/IExposureDataRepository.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/ViewModels/ExposureCheck/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
  Covid19Radar/Covid19Radar/Views/HomePage/ExposuresPage.xaml
Labels: enhancement, design

#889 基準値未満の接触画面リファインメント
  Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx
  Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposureCheckPageViewModel.cs
  Covid19Radar/Covid19Radar/Views/HomePage/ExposureCheckPage.xaml
Labels: COCOA2, beta

#895 Improve English and Chinese translation.
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
Labels: COCOA2, beta

#894 Improve English and Chinese translation.
  Covid19Radar/Covid19Radar/Resources/AppResources.resx
  Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx
  Covid19Radar/Covid19Radar/Views/HomePage/ContactedNotifyPage.xaml
Labels: COCOA2

#896 Bump up version to v2.0.0-beta04(closed)
  Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs
Labels: COCOA2, beta
